---
- hosts: all
  become: yes
  become_user: root
  vars:
    mysql_root_user: root
    mysql_root_password: redhat

  tasks:
  - name: install MySQL
    yum: name={{ item }} state=present
    with_items:
    - MySQL-python
    - mariadb-server
    notify: fire mysql 

  - name: ensure MySQL starts on boot
    service: name=mariadb enabled=yes state=started

  - name: lock down root user
    mysql_user:
      check_implicit_admin=yes
      login_user="{{mysql_root_user}}"
      login_password="{{mysql_root_password}}"
      name="{{mysql_root_user}}"
      password="{{mysql_root_password}}"
      host="{{item}}"
      priv="*.*:ALL,GRANT"
    with_items:
      - "localhost"
      - "{{ansible_default_ipv4.address}}"
      - "{{ansible_fqdn}}"
      - "{{ansible_hostname}}"

  handlers:
  - name: fire mysql
    service: name=mariadb state=restarted

