---
# tasks file for mysql-server
- name: install MySQL
  become: yes
  become_user: root
  yum: name=mysql-server state=present

- name: ensure MySQL starts on boot
  become: yes
  become_user: root
  service: name=mysqld enabled=yes state=started

- name: lock down root user
  mysql_user:
    check_implicit_admin=yes
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    name="{{mysql_root_user}}"
    password="{{mysql_root_password}}"
    host="{{item}}"
    priv="*.*:ALL,GRANT"
  with_items:
    - "localhost"
    - "{{ansible_default_ipv4.address}}"
    - "{{ansible_fqdn}}"
    - "{{ansible_hostname}}"
